# Generated by Django 4.0.6 on 2022-08-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='DAys',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='Trainer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
