# Generated by Django 4.0.6 on 2022-08-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormValidations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('Phn_no', models.IntegerField()),
                ('feedback', models.TextField(max_length=255)),
            ],
        ),
    ]
